GlobeFA.Web/Controllers/ContactsController.cs
using GlobeFa.DAL.Entities;
using GlobeFa.DAL.EntitiesDTO;
using GlobeFa.DAL.Repository;
using GlobeFa.Infrastructure.Services;
using System;
using System.Linq;
using System.Web.Mvc;

namespace GlobeFA.Web.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactService _contactService = new ContactService(new UnitOfWork());
        private readonly EmployeeService _employeeService = new EmployeeService(new UnitOfWork());

        public ActionResult ContactDetails()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetAllContactsToGrid()
        {
            var contacts = _contactService.GetContacts("Employee");

            var empDtoList = contacts.Select(obj => new ContactDto
            {
                Id = obj.Id,
                EmployeeName = obj.Employee.FirstName + " " + obj.Employee.MiddleName + " " + obj.Employee.LastName,
                EmployeeNumber = obj.Employee.EmployeeNumber,
                ContactMobile = obj.ContactMobile,
                ContactHome = obj.ContactHome,
                ContactCountryCode = obj.ContactCountryCode,
                Address1 = obj.Address1,
                Address2 = obj.Address2,
                City = obj.City,
                Country = obj.Country,
                PostalCode = obj.PostalCode,
                EmailPersonal = obj.EmailPersonal,
                EmailWork = obj.EmailWork
            });
            return Json(empDtoList.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CreateOrUpdateContact(ContactDto dtoObj)
        {
            var emp = _employeeService.GetEmployeeById(1);
            var contactExist = _contactService.GetContactById(dtoObj.Id);
            if (contactExist == null)
            {
                var contactNew = new Contact
                {
                    EmployeeId = 1,
                    ContactMobile = dtoObj.ContactMobile,
                    ContactHome = dtoObj.ContactHome,
                    ContactCountryCode = dtoObj.ContactCountryCode,
                    Address1 = dtoObj.Address1,
                    Address2 = dtoObj.Address2,
                    City = dtoObj.City,
                    Country = dtoObj.Country,
                    PostalCode = dtoObj.PostalCode,
                    EmailPersonal = dtoObj.EmailPersonal,
                    EmailWork = dtoObj.EmailWork,
                    DateCreated = DateTime.Now,
                    DateModified = DateTime.Now
                };
                var contactAdded = _contactService.AddContact(contactNew);
                return Json(contactAdded);
            }

            contactExist.ContactMobile = dtoObj.ContactMobile;
            contactExist.ContactHome = dtoObj.ContactHome;
            contactExist.ContactCountryCode = dtoObj.ContactCountryCode;
            contactExist.Address1 = dtoObj.Address1;
            contactExist.Address2 = dtoObj.Address2;
            contactExist.City = dtoObj.City;
            contactExist.Country = dtoObj.Country;
            contactExist.PostalCode = dtoObj.PostalCode;
            contactExist.EmailPersonal = dtoObj.EmailPersonal;
            contactExist.EmailWork = dtoObj.EmailWork;
            contactExist.DateModified = DateTime.Now;
            var contactUpdated = _contactService.UpdateContact(contactExist);
            return Json(contactUpdated);
        }
    }
}

GlobeFA.Web/Controllers/EmployeesController.cs
using GlobeFa.DAL.Entities;
using GlobeFa.DAL.EntitiesDTO;
using GlobeFa.DAL.Repository;
using GlobeFa.Infrastructure.Services;
using System;
using System.Linq;
using System.Web.Mvc;

namespace GlobeFA.Web.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly EmployeeService _employeeService = new EmployeeService(new UnitOfWork());
        private readonly ContactService _contactService = new ContactService(new UnitOfWork());

        public ActionResult EmployeeDetails()
        {
            return View();
        }


        [HttpGet]
        public ActionResult GetAllEmployeesToGrid()
        {
            var employees = (from emp in _employeeService.GetEmployees()
                             join con in _contactService.GetContacts() on emp.Id equals con.Employee.Id
                             select new { emp, con }).ToList();

            var allEmployees = (User.IsInRole("Admin"))
                ? employees
                : employees.Where(e => e.emp.IsActive == true);

            var empDtoList = allEmployees.Select(obj => new EmployeeDto
            {
                Id = obj.emp.Id,
                FirstName = obj.emp.FirstName,
                MiddleName = obj.emp.MiddleName,
                LastName = obj.emp.LastName,
                Mobile = obj.con.ContactMobile,
                Email = obj.con.EmailPersonal,
                NIC = obj.emp.NICNumber,
                IsActive = obj.emp.IsActive,
                EmployeeNumber = obj.emp.EmployeeNumber
            }).ToList();
            return Json(empDtoList.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CreateOrUpdateEmployee(EmployeeDto empDto)
        {
            var empObj = new Employee
            {
                Id = empDto.Id,
                FirstName = empDto.FirstName,
                MiddleName = empDto.MiddleName,
                LastName = empDto.LastName,
                Initials = empDto.Initials,
                Title = empDto.Title,
                Gender = empDto.Gender,
                DateOfBirth = empDto.DateOfBirth,
                NICNumber = empDto.NIC,
                EmploymentType = empDto.EmploymentType,
                RoleTypeDes = empDto.RoleTypeDes,
                UserGroup = empDto.UserGroup,
                MaritalStatus = empDto.MaritalStatus,
                IsActive = empDto.IsActive
            };

            var employeeCheck = _employeeService.GetEmployeeById(empDto.Id);
            if (employeeCheck == null)
            {
                empObj.EmployeeNumber = _employeeService.GenerateEmployeeNumber();
                empObj.DateCreated = DateTime.Now;
                empObj.DateModified = DateTime.Now;

                var emp = _employeeService.AddEmployee(empObj);
                var conStat = _contactService.AddContact(new Contact { EmployeeId = empObj.Id });

                return Json(emp);
            }
            empObj.EmployeeNumber = employeeCheck.EmployeeNumber;
            empObj.DateCreated = employeeCheck.DateCreated;
            empObj.DateModified = DateTime.Now;
            var empUpdated = _employeeService.UpdateEmployee(empObj);
            return Json(empUpdated);
        }

        [HttpPost]
        public ActionResult DeleteEmployee(Employee employee)
        {
            bool isMapped = HaveDependencies(employee);
            if (isMapped)
            {
                return null;
            }
            else
            {
                var empDeleted = _employeeService.DeleteEmployeeById(employee.Id);
                return Json(empDeleted);
            }
        }

        //ToDo: check dependencies here
        public bool HaveDependencies(object obj)
        {
            return true;
        }
    }
}

GlobeFA.Web/Controllers/TenantsController.cs
using GlobeFa.DAL.Repository;
using GlobeFa.Infrastructure.Services;
using System.Web.Mvc;

namespace GlobeFA.Web.Controllers
{
    public class TenantsController : Controller
    {
        private readonly TenantService _employeeService = new TenantService(new UnitOfWork());
        private readonly ContactService _contactService = new ContactService(new UnitOfWork());

        public ActionResult TenantDetails()
        {
            return View();
        }

        //[HttpGet]
        //public ActionResult GetAllTenantsToGrid()
        //{
        //    var tenants = (from tnt in _tenantService.GetTeants()
        //                     join con in _contactService.GetContacts() on tnt.Id equals con.Tenant.Id
        //                     select new { tnt, con }).ToList();

        //    var allTenants = (User.IsInRole("Admin"))
        //        ? tenants
        //        : tenants.Where(e => e.tnt.IsActive == true);

        //    var empDtoList = allTenants.Select(obj => new EmployeeDto
        //    {
        //        Id = obj.emp.Id,
        //        FirstName = obj.emp.FirstName,
        //        MiddleName = obj.emp.MiddleName,
        //        LastName = obj.emp.LastName,
        //        Mobile = obj.con.ContactMobile,
        //        Email = obj.con.EmailPersonal,
        //        NIC = obj.emp.NICNumber,
        //        IsActive = obj.emp.IsActive,
        //        EmployeeNumber = obj.emp.EmployeeNumber
        //    }).ToList();
        //    return Json(empDtoList.ToList(), JsonRequestBehavior.AllowGet);
        //}
    }
}

GlobeFA.Web/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | eApartment</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/vendor")
    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Module","Home")">eApartment - Apartment Management System</a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    @Html.Partial("_LoginPartial")
                </li>
            </ul>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default e_btn" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </li>
                        <li>
                            <a class="active" href="@Url.Action("Index","Home")"><i class="fa fa-home fa-fw"></i> Home</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="#"><i class="fa fa-user-md fa-fw"></i> Stakeholders<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="@Url.Action("EmployeeDetails", "Employees")"><i class="fa fa-group fa-fw"></i> Employees</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("TenantDetails", "Tenants")"><i class="fa fa-user fa-fw"></i> Tenants</a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("ContactDetails", "Contacts")"><i class="fa fa-book fa-fw"></i> Contacts</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="#"><i class="fa fa-building-o fa-fw"></i> Apartments<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href=""><i class="fa fa-building fa-fw"></i> Class 1</a>
                                    </li>
                                    <li>
                                        <a href=""><i class="fa fa-building fa-fw"></i> Class 2</a>
                                    </li>
                                    <li>
                                        <a href=""><i class="fa fa-building fa-fw"></i> Class 3</a>
                                    </li>
                                    <li>
                                        <a href=""><i class="fa fa-building fa-fw"></i> Suite</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Reports<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href=""> <i class="fa fa-list"></i> Apartment Registry</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div ng-app="app">
            @RenderBody()

            <hr />
            <footer></footer>
        </div>
    </div>

</body>
</html>

GlobeFA.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title | GlobeFA</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="~/Content/sb-admin-2.css" rel="stylesheet">
    <link href="~/fonts/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <script type="text/javascript">
        $(document).ready(function () {

            $('#uname').click(function (event) {
                $('#uname').val('');
                if ($("#error") != 'undefined') {
                    $("#error").hide();
                }
            });
            $('#upwd').click(function (event) {
                $('#upwd').val('');
                if ($("#error") != 'undefined') {
                    $("#error").hide();
                }
            });
        });

        //login with enter button
        function loginByEnter(e) {
            var code = e.keyCode;
            if (code == 13) {
                checkform();
            }
        }

        function checkform(obj) {
            var UserName = document.getElementById('uname').value;
            var Pass = document.getElementById('upwd').value;
            var remember = $('#chck_rememberme_id').is(':checked');

            if (UserName == '' || Pass == '' || UserName == 'User Name' || Pass == '******') {
                document.getElementById('uname').style.borderColor = '#F00';
                document.getElementById('upwd').style.borderColor = '#F00';
                document.getElementById('error').style.display = 'block';
                document.getElementById('error').innerHTML = 'Invalid Username or Password';
            } else {
                $('#uname').attr("disabled", "disabled");
                $('#upwd').attr("disabled", "disabled");
                $('#btnLogin_id').attr("disabled", "disabled");
                $('#btnLogin_id').text('logging in, please wait');

                $.ajax({
                    type: 'POST',
                    url: '/Account/Login?username=' + UserName + '&password=' + Pass + '&remember=' + remember,
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json',
                    success: function (res) {
                        if (res.indexOf('Successfully Logged In|Dealer') > -1) {
                            location.href = '/Home/Index';
                        }
                        else {
                            $('#uname').removeAttr("disabled");
                            $('#upwd').removeAttr("disabled");
                            $('#btnLogin_id').removeAttr("disabled");
                            $('#btnLogin_id').text('Log In');
                            document.getElementById('error').style.display = 'block';
                            document.getElementById('error').innerHTML = res;
                        }
                    },
                    failure: function (error) {
                        document.getElementById('error').style.display = 'block';
                        document.getElementById('error').innerHTML = 'error';
                    }
                });
            }
        }

    </script>

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.11.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins/metisMenu/metisMenu.min.js"></script>
    <script src="~/Scripts/sb-admin-2.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

GlobeFA.Web/Views/Shared/_LayoutModule.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title | GlobeFA</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="~/Content/sb-admin-2.css" rel="stylesheet">
    <link href="~/fonts/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/Site.css" rel="stylesheet" />

</head>
<body>
    <div class="container">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.11.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins/metisMenu/metisMenu.min.js"></script>
    <script src="~/Scripts/sb-admin-2.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>